LakeAffectedBlog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('events.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from . import views
from .views import Exclusive_Detail
from .views import Event_Detail


app_name = 'events'
urlpatterns = [
    path('today', views.home, name="home"),
    path('blog', views.blog, name="blog"),
    path('', views.fullWeek, name="full-week"),
    path('aboutUs', views.aboutUs, name="aboutUS"),
    path('register', views.register, name="register"),
    path('event-form',views.eventForm, name="event-form"),
    path('recent_video',views.Recentvideo,name="recent_video"),
    path('music-form', views.musicform, name="music-form"),
    path('discord-invite', views.discord,name='discord-invite'),
    path('full-blog', views.fullblog,name='full-blog'),
    path('blog/<slug>',Exclusive_Detail.as_view(), name='exclusive_blog'),
    path('diy-zone',views.diy, name="diy-zone"),
    path('contact', views.contact, name="contact"),
    path('<slug>', Event_Detail.as_view(),name='event_detail_view'),
 

]

events/models.py
from django.db import models
from django.template.defaultfilters import slugify
from datetime import datetime, date


# class LAUSERS(models.Model):
#     username = models.CharField("User-Name",max_length=120)
#     email = models.EmailField("Emails")
#     def __str__(self):
#         return self.username



class Event(models.Model):
    CATEGORIES = (
    ("Show", "show"),
    ("Gallery", "gallery"),
    ("Bar", "bar"),
    ("Pop-up", "pop-up"),
    ("Other", "other"),
)
    name = models.CharField("Event Name", max_length=120)
    event_date= models.DateTimeField("Event Date")
    location = models.CharField("Event Location", max_length=120, blank=True)
    description = models.TextField("Event Description")
    fbLink = models.URLField("Social Media Link", blank=True)
    flyer = models.ImageField(upload_to="media/flyers", blank=True)
    slug = models.SlugField(max_length=200,unique=True, null=True)
    category = models.CharField('Category',  max_length=120, choices= CATEGORIES ,default="show")
    musicLinks = models.TextField("Bandcamp Link" , blank=True)
    # attending = models.ManyToManyField(LAUSERS, blank=True)

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(Event,self).save(*args, **kwargs)



# class Item(models.Model):
#     name = models.CharField('Video name', max_length=100, null=True)
#     video = EmbedVideoField(verbose_name="myVideo")  # same like models.URLField()
#     def __str__(self):
#         return self.name


class FormEvent(models.Model):
    name = models.CharField("Event Name", max_length=120)
    event_date= models.DateTimeField("Event Date")
    location = models.CharField("Event Location", max_length=120, blank=True)
    description = models.TextField("Event Description")
    fbLink = models.URLField("FB Link", blank=True)
    flyerLink = models.URLField("FlyerLink", blank=True)
    # attending = models.ManyToManyField(LAUSERS, blank=True)

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(FormEvent,self).save(*args, **kwargs)

class MostRecentVideo(models.Model):
    name = models.CharField("Vid Name", max_length=120,default="")
    vidlink = models.URLField("Video Url", blank=True)

    def __str__(self):
        return self.name

    def save(self,*args,**kwargs):
        super(MostRecentVideo,self).save(*args, **kwargs)

class BlogPostQueryset(models.QuerySet):

    def published(self):
        return self.filter(published=True)
       
      

    def draft(self):
        return self.filter(published=False)



   


class BlogPost(models.Model):
    title = models.CharField("Post Title", max_length=120)
    cover = models.ImageField("Cover Art",upload_to="media/blog-Covers")
    body = models.TextField("Body")

    videoLink = models.URLField("Video Link")

    favSongTitle= models.CharField("Favorite Song 1", max_length=120,blank=True)
    favSongUrl= models.URLField("Song URL 1", max_length=120,blank=True)

    favSongTitle2= models.CharField("Favorite Song 2", max_length=120,blank=True)
    favSongUrl2= models.URLField("Song URL 2", max_length=120,blank=True)

    favSongTitle3= models.CharField("Favorite Song", max_length=120,blank=True, default=", ")
    favSongUrl3= models.URLField("Song URL 3", max_length=120,blank=True ,default=", ")
    
    page = models.CharField("Post ID", max_length=120,default="Band-Name")
    relatedArtist = models.CharField("Similar Artists",max_length=120,default="The Strokes", blank=True)
    instaLink = models.URLField("Insta URL" ,blank=True)
    twitterLink = models.URLField("Twitter URL" ,blank=True)
    bandcampLink = models.URLField("Bandcamp URL", blank=True)
    soundcloudLink = models.URLField("Soundcloud URL" ,blank=True)
    audiusLink = models.URLField("Audius URL" ,blank=True)
    published = models.BooleanField("published", default=False)
    objects = BlogPostQueryset.as_manager()

    def __str__(self):
        return self.title

   





class FavSongs(models.Model):
    name = models.CharField("Song name", max_length=120, blank=True)
    url = models.CharField("Timestamp", max_length=120,blank=True )
    songtag = models.OneToOneField(BlogPost ,on_delete=models.CASCADE)

    def __str__(self):
        return self.name
    



class MusicForm(models.Model):
    name= models.CharField("Artist Name", max_length=120)
    email= models.EmailField("Artist Email")
    release_date = models.DateTimeField("Release Date")
    link = models.URLField("Music Link", blank=True)
    description = models.TextField("Descripton", blank=True)


class Email(models.Model):
    email= models.EmailField("Email")

class Discord(models.Model):
    email = models.EmailField("Email")
    music = models.URLField("Music")

   


class Exclusive(models.Model):
    name = models.CharField("Post Title", max_length=120)
    cover = models.ImageField("Cover Art",upload_to="media/blog-Covers")
    body = models.TextField("Body")
    interviewer = models.TextField("Interviewer")
    videoLink = models.URLField("Video Link")

    favSongTitle= models.CharField("Favorite Song 1", max_length=120,blank=True)
    favSongUrl= models.URLField("Song URL 1", max_length=120,blank=True)

    favSongTitle2= models.CharField("Favorite Song 2", max_length=120,blank=True)
    favSongUrl2= models.URLField("Song URL 2", max_length=120,blank=True)

    favSongTitle3= models.CharField("Favorite Song", max_length=120,blank=True, default=", ")
    favSongUrl3= models.URLField("Song URL 3", max_length=120,blank=True ,default=", ")
    
    slug = models.SlugField(max_length=200,unique=True, null=True)
    published = models.BooleanField("published", default=False)
    objects = BlogPostQueryset.as_manager()

    def __str__(self):
        return self.name
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.name)
        super(Exclusive,self).save(*args, **kwargs)

    

events/forms.py
from django import forms
from django.forms import ModelForm
from .models import FormEvent
from .models import MusicForm
from .models import Email
from .models import Discord

class Recieved_Events(ModelForm):
    class Meta:
        model = FormEvent
        fields = ('name', 'event_date', 'location', 'flyerLink', 'description', )
        labels={
            'name':'',
            'event_date' :'',
            'location':'',
            'description':'',
            'flyerLink':'',


        }
        widgets = {

            'name': forms.TextInput(attrs={'class':'form-control ','placeholder':'Event Name','max-width':'10rem' } ),
            'event_date': forms.TextInput(attrs={'class':'form-control','placeholder':'Event Date'}),
            'location': forms.TextInput(attrs={'class':'form-control','placeholder':'Location'}),
            'description': forms.Textarea(attrs={'class':'form-control','placeholder':'Description'}),
            'flyerLink':forms.TextInput(attrs={'class':'form-control','placeholder':'Image (Social Media Link)'}),

        }

class EmailList(ModelForm):
   class Meta:
        model = Email
        fields = ("email",)
        labels= {
            'email': '',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class':'form-control','placeholder':'Email','max-width':'20rem'} ),
        }




class Recieved_Music(ModelForm):
    class Meta:
        model = MusicForm
        fields = ('name', 'email', 'release_date', 'link', )
        labels={
            'name':'',
            'email' :'',
            'release_date':'',
            'link':'',
          
        }
        widgets = {

            'name': forms.TextInput(attrs={'class':'form-control','placeholder':'Artist Name','max-width':'20rem'} ),
            'email': forms.TextInput(attrs={'class':'form-control','placeholder':'Email'}),
            'release_date': forms.TextInput(attrs={'class':'form-control','placeholder':'Release Date'}),
            'link': forms.TextInput(attrs={'class':'form-control','placeholder':'Link'}),
            
        }


class Discord_Invite(ModelForm):
    class Meta:
        model = Discord
        fields = ("email", "music")
        labels= {
            'email': '',
            'music': '',
        }
        widgets = {
            'email': forms.TextInput(attrs={'class':'form-control','placeholder':'Email','max-width':'20rem'} ),
            'music': forms.TextInput(attrs={'class':'form-control','placeholder':'Link to Music','max-width':'20rem'} ),
        }

events/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic.detail import DetailView
from .models import Event
from django.utils import timezone
import datetime
from .models import MostRecentVideo
from .forms import EmailList
from django.core.mail import send_mail, BadHeaderError
from .forms import Recieved_Events
from .forms import Recieved_Music
from .models import BlogPost
from django.http import HttpResponseRedirect,HttpResponse
from django.contrib.auth.forms import UserCreationForm
from .models import FavSongs
from .models import Discord
from .models import Exclusive
from .forms import Discord_Invite
# Create your views here.

# def all_events(request):
#
#     return render(request, "events/blog.html", {'event'})


class Event_Detail(DetailView):
    model = Event

    def get_context_data(self, **kwargs):
        context = super(Event_Detail,self).get_context_data(**kwargs)
        return context


class Exclusive_Detail(DetailView):
    model = Exclusive

    def get_context_data(self, **kwargs):
        context = super(Exclusive_Detail,self).get_context_data(**kwargs)
        return context

def exclusive_blog(request,slug):
    # post = get_object_or_404(Exclusive, slug=slug)
    return render(request, "events/exclusive_blog.html", {})

def event_detail(request,slug):
    return render(request, "events/event_detail.html", {})

def Recentvideo(request):
    vid = MostRecentVideo.objects.all()
    return render(request,'events/recent_video.html',{'vid': vid})

def diy(request):
    return render(request, "events/diy-zone.html", {})

def contact(request):
    return render(request, "events/contact.html", {})


def home(request):
    # event_list = Event.objects.all()
    # today = datetime.now()
    vid = MostRecentVideo.objects.all()
    event_list = Event.objects.all().filter(event_date__gte=timezone.now().replace(hour=0, minute=0, second=0), 
    event_date__lte=timezone.now().replace(hour=23, minute=59, second=59))
    return render(request,'events/index.html', {'event_list': event_list, 'vid':vid}, )

def fullWeek(request):
    # event_list = Event.objects.all()
    # today = datetime.now()
    event_list = Event.objects.all().order_by('event_date')
    return render(request,'events/full-week.html', {'event_list': event_list})

def eventForm(request):
    submitted= False
    if request.method == "POST":
        form=Recieved_Events(request.POST)
        if form.is_valid:
            form.save()
            return HttpResponseRedirect('/event-form?submitted=True')
    else:
        form = Recieved_Events
        if 'submitted' in request.GET:
            submitted=True


    form = Recieved_Events
    return render(request,'events/event-form.html',  {'form':form, 'submitted':submitted})



def blog(request):
   
    blog = BlogPost.objects.all()
    blog = BlogPost.objects.filter(published=True).order_by('-id')[:25]
    eBlog = Exclusive.objects.all()
    
    # blog = BlogPost.objects.order_by('-id')
    return render(request,'events/blog.html', {'blog': blog, 'eBlog': eBlog},)


def fullblog(request):
   
    blog = BlogPost.objects.all()
    blog = BlogPost.objects.filter(published=True).order_by('-id')
  
    
    # blog = BlogPost.objects.order_by('-id')
    return render(request,'events/full-blog.html', {'blog': blog})


def aboutUs(request):
    return render(request, "events/aboutUs.html", {})


def discord(request):
    if request.method == "GET":
        form = Discord_Invite
    else:
        form = Discord_Invite(request.POST)  
        if form.is_valid():   
            name = form['email'].value()
            email = form['email'].value()
            message = form['email'].value() + '\n' + form['music'].value()
              
            try:
                send_mail(name,message,email,['lakecurrents@gmail.com'])
                return HttpResponseRedirect('/discord-invite?submitted=True')
            except BadHeaderError:
                return HttpResponse('Invalid header found.')  
    return render(request, "events/discord-invite.html", {'form': form,})
    

def register(request):
    form = UserCreationForm(request.POST)
    if form.is_valid():
        form.save()
    return render(request,'events/register.html', {"form":form})

# def home(request):
#     submitted =  False
#     if request.method == "POST":
#         form=EmailList(request.POST)
#         if form.is_valid:
#             form.save()
#         return HttpResponseRedirect('/?submitted=True')    
#     else:
#         form = EmailList
#         if 'submitted' in request.GET:
#             submitted=True

#     form = EmailList    
#     return render(request,'events/home.html', {'form': form,'submitted' : submitted})

def musicform(request):
 
    if request.method == "GET":
        form = Recieved_Music
    else:
        form = Recieved_Music(request.POST)  
        if form.is_valid():   
            name = form['name'].value()
            email = form['email'].value()
            message = form['name'].value() + '\n' + form['email'].value() + '\n' +  form['release_date'].value() +'\n' + form['link'].value() +'\n' 
              
            try:
                send_mail(name,message,email,['lakecurrents@gmail.com'])
                return HttpResponseRedirect('/music-form?submitted=True')
            except BadHeaderError:
                return HttpResponse('Invalid header found.')
    return render(request, 'events/music-form.html', {'form': form})
           

            
            
   
    

events/templates/events/aboutUs.html
{% extends 'events/base.html' %}
{% load static %}
{% block content%}
<style>
  @font-face {
  
  font-family: 'kiki';
  src: url('{% static 'fonts/brawl.otf' %}') format("opentype");
  }

  .h1{
      font-family: stat;
  }

  .container
  {
      background-color: #1d1d1d;
      border-radius: 18px;
      font-family: kiki;
  }

  .p
  {
    font-family: kiki;
    font-size: clamp(6px, 1vw, 20px); 
  }


</style>

<div class="text-center">
    <img src="{% static '/buttons/aboutusheader.png' %}" class="img-fluid" style="width: clamp(900px,70%,1200px);
    height: clamp(30%,8vw,1200px);">
  </div>

<div class="container text-center text-white">
</br>

<p>
    Lake Affected is a Chicago music/media center for locating and unveiling the hidden talents that exist within the city. 
As big advocators of localism we wish more people would look to their local scenes to grow and support artists which drive the cultural movements in and outside the city they orignate from. 
Our hope is to give people easier access and insight into the music and art web that spans the whole city. 
We believe that thinking and engaging with art that is produced in the same region and time can open up wonderful relationships and interesting cultural movements that will last in the temporal internet age.
Here in Chicago, we are all Lake Affected. 

<p>
  For any questions/improvements/collabs let us know at lakeaffectedrecords@gmail.com or dm us on any social media accounts!
  
  Wallets:
</br>
</br>
BTC: 3Ei3hiG8f1DayJoRbMkmqYiwqcidXzUFKL
ETH:  0x6E27C21dF36928D8F5144082382f4D8EEcb34Fb9
AUDIO: 0xc8906bbe62e846205e01e5b7415223cf40be5f7d

</p>


</p>
</br>

</div>








{% endblock %}

events/templates/events/discord-invite.html
{% extends 'events/base.html' %}
{% load static %}
{% block content %}

<style>
  @media only screen and (max-width: 600px) {
    #header
    {
      visibility: hidden;
    }
  }
  
  @font-face {
  
  font-family: 'stat';
  src: url('{% static 'fonts/ro.ttf' %}') format("truetype");
  }
  
  
  #main
  {
      background: rgba(0, 0, 0.5, 0.3);
      box-shadow:1px 1px 4px #000000;
      border: whitesmoke;
  }
  
  #header
  {
      font-family: stat;
      color: white;
      background-image: url("{% static 'images/backer.png'%}");
      margin-bottom: 10px;
      margin-top: 50px;
    box-shadow:1px 1px 4px #000000;
  }
  </style>
  <center>
  <div class="text-center" id="header">
      <img src="{% static '/buttons/invite.png' %}" class="img-fluid" style="width: clamp(900px,70%,1200px);
      height: clamp(30%,8vw,1200px);">
    </div>
    
  </br>


<div class="modal fade bd-example-modal-sm" id="submitted" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-sm ">
      <div class="modal-content text-center bg-dark text-white" style="padding-top: 10px; padding:10px">
        Thank you! The invitation will be sent shortly!
      </br>
      </div>
    </div>
  </div>
  

<div class="container py-3 px-3 px-sm-1 bg-transparent text-justify"  id="main" style="max-width: 50rem; min-height: 250px; border-radius: 15px;">
  <form action="" method="POST">
      {% csrf_token %}
      {{form.as_p}}
      <input type="submit" value="Submit" class="btn btn-outline-light" style="width: 70%;"> 
     
  </form>
  </center>
  </div>



<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    



    <script>
      let win = window.location.search;

      if (win != "?submitted=True")
      {
        $('#submitted').modal('hide');
       
        console.log(win);
     
      }

      else
      {
        $('#submitted').modal('show');
      }
   
      

    </script>
{% endblock %}

events/templates/events/index.html
{% extends 'events/base.html' %}

{% load static %}

{% block content %}
<link
rel="stylesheet"
href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.1.1/animate.min.css"
/>
<style>
  @font-face {

    font-family: 'stat';
    src: url('{% static 'fonts/ro.ttf' %}') format("truetype");
  }

  @media only screen and (max-width: 600px) {
    .container1
    {
      
      background-image: url("{% static 'images/back500.png'%}");
    }
  }

  .head {
    font-family: stat;
    font-size: x-large;
    color: white;
    background-color: rgb(51, 51, 50);
  }

  .head:hover {}

  .card
  {
    border: 0px;
    background: rgba(0, 0, 0.5, 0.3);
    color: white;
    font-weight: 200;
    
  
   
  }

  .card .card-body
  {
    opacity: 80%;
    
  }

  .container
  {
    position: relative;
    text-align: left;
    padding: 0px;
    padding-bottom: 0px;
    font-size: 0px;
    
  }

  .type
  {
    position: absolute;
  bottom: 0px;
  left: 25px;
  padding:0;
  padding-bottom: 0px;
  font-weight: bolder;
  color: white;
  font-size: 15px;
  text-rendering: optimizeLegibility;
  pointer-events: none;
  
  }
  

  .a:hover {text-decoration: none;}

  .card > .card-img-top:hover
  {
    filter: brightness(75%);
  }

  .card-img-top:hover
  {
    filter: brightness(75%);
  }


  .container1
    {
      display: grid;
      grid-template-columns: 1fr 1fr 1fr 1fr;
      grid-template-rows: 1fr;
      height:150px;
      background-color:transparent;
      padding-bottom: 0;
      font-size: 0px;
      background-image: url("{% static 'images/backer.png'%}");
      margin-top: 60px;
      box-shadow:1px 1px 4px #000000;
    }
    .box
    {
    background-image: url("{% static 'images/f1.png'%}");
    background-repeat: no-repeat;
    background-size:contain;
    background-position: center;
    grid-column-start: 4;
    opacity: 0.9;
    grid-column-end: 2;
    grid-row-start: 1;
    z-index: 1;
    
    padding-top: 0px;
    }

    #footer
{
  padding:  20px;
  position: absolute;
  background:  #4e5245;
 bottom: 0;
 width: 100%;
  
}


    .left-content
    {
    background-image: url("{% static 'images/h4.png'%}");
    background-repeat: no-repeat;
    background-size:contain;
    background-position: center ;
    grid-column-start: 4;
    grid-column-end: 2;
    grid-row-start: 1;
    z-index: 4;
    width: 1fr;
    
    }

    
    .btn {
      border-style: outset;
}


    #event-title
    {
      text-shadow: 2px 2px 4px #000000;
    
    }

    #twitter
    {
     text-align: center;
     position: relative;
     width: 20px;
     height: 20px;
    }

    #typetag:hover
    {
      opacity: .5;
    }

    #week
    {
      opacity: .8;
      
    }

    .card-img-top
  {
    transition: all .2s !important;
  }

  #zzz
  {
    display: none;
  }

  .container1:hover
    {
      filter: brightness(120%);
    }

 
}
</style>


<!-- <div class="embed-responsive embed-responsive-16by9 text-justify  py-4 px-5 px-sm-3 bg-light mx-auto" style="background-image: url('{% static 'images/ggga.gif' %}' )"  > -->
<!-- <div class="col text-center">
  <div>
  </div>
  <p></p>
  <iframe width="420" height="315" src="{{v.vidlink}}" title="YouTube video player" frameborder="0"
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
    allowfullscreen></iframe>
  <p class="head">Latest:</p>
</div> -->

<a href="https://www.youtube.com/channel/UCGYUEmkgMxEcCtnbmSLVxOg" target="_blank">
  <div class="container1">
    <div class="box"></div>

     <div class="left-content animate__animated animate__bounceInLeft" > </div>
     
     
     <div class= "bottom-content text-center" style="margin: 0px;">"Lake Affected is uncovering Chicago's new sound...without an algorithm"</div>
  </div>
</a>

<p></p>

<div class="text-center animate__animated animate__fadeIn" id="zzz">
  <img src="{% static 'icons/zzz.gif' %} ">
  <p style="color:white"> No events today. See the full week &#128064</p>
</div>
{% for event in event_list %}
<!-- <link href= "{% static '/css/style.css' %}" rel="stylesheet"> -->
</br>

  <div class="card mx-auto text-center shadow border border-dark align-self-center" id="main-body" style="max-width: 900px; max-height: 34rem; border-radius: 2px;">
    <a  href="{% url 'events:event_detail_view' slug=event.slug%}" class="">
    <img src="{{ event.flyer.url }}" class="card-img-top" alt="..."  style="max-height: 200px; object-fit: cover; "/>
  </a>
  <div class= container>
  <img src="{% static 'icons/typetag.png' %} " id="typetag" style="width: 80px; height: 20px; margin: 0px;" >
  <div class="type" >{{event.category}}</div>
  </div>
    <div class="card-body">
      <h5 class="card-title text-decoration-none " id="event-title" > {{event.name}} 
        
      </h5>
      <p class="card-text">{{event.event_date}}</p>
      <p class="card-text" id="location">{{event.location}}
        <a data-toggle="tooltip" data-placement="top" id = "copy-button" title="Copy Address!">
      <img src="{% static 'icons/copy2.png' %} " style="width: 18x; height: 18px;">
        </a>
    </p>
   <a  href="{% url 'events:event_detail_view' slug=event.slug%}" class=""></a>
   <a href="{% url 'events:event_detail_view' slug=event.slug%}" class="btn btn-outline-light " style="width:50%; border-radius: px;">Details</a>
    </div>
   
   
  </div>





<!-- 
<div class="card  text-black mb-4 mx-auto bg-dark" style="max-width: 55rem;
 border-radius: 30px; border: none; ">
  <div class="card-img"></div>
  <div class="card text-center">
    <div class="card-header">
      Today
    </div>
    <div class="card-body">
      <h5 class="card-title"> {{event.name}} </h5>
      <p class="card-text">{{event.event_date}}</p>
      <p class="card-text">{{event.location}}</p>
      <a href="{% url 'events:event_detail_view' slug=event.slug%}" class="btn btn-outline-dark">Details</a>

    </div>
  </div>
</div> -->


{%endfor%}
</br>

  <div class="col text-center" style="position: relative;">
    <a href="/#" class="btn btn-outline-light mx-auto " id="week" style="width:40%">See Full Week</a>

    </a>

    
  </div>
  </br>

</div>

</div>


</div>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
<!-- <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script> -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<script>

$(function () {
  $('[data-toggle="tooltip"]').tooltip({ trigger: "hover" })
})


var main = document.querySelector("#main-body");

if (main == undefined)
{
$("#zzz").css("display","block");
}





function Clipboard_CopyTo(value) {
  var tempInput = document.createElement("input");
  tempInput.value = value;
  document.body.appendChild(tempInput);
  tempInput.select();
  document.execCommand("copy");
  document.body.removeChild(tempInput);
}

const locations = document.querySelectorAll('#location');
const copy = document.querySelectorAll('#copy-button');
for (let i = 0; i < locations.length; i++) {
    locations[i].addEventListener('click', e => {
        {
          Clipboard_CopyTo(locations[i].textContent)
          $(copy).attr('data-bs-original-title','Copied!');
          $(copy[i]).tooltip('show')
          $(copy).attr('data-bs-original-title','Copy Address');

        }
    }
)

}
  
</script>


{% endblock %}

events/templates/events/recent_video.html
{% load static %}




<div class="embed-responsive embed-responsive-16by9 text-justify  py-4 px-5 px-sm-3 bg-light mx-auto" style="background-image: url('{% static 'images/head.png' %}')   " >
    <div class="col text-center">
    <div>
            <!-- <link href= "{% static '/css/stylesheet' %}" rel="stylesheet"> -->
            <p class="fw-bold" style="font-size: larger;">Latest: </p>
        </div>
        <p></p>
    <iframe width="420" height="315" src="" title="YouTube video player" frameborder="0" 
    allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
  
  </div>
</div>

events/templates/events/vid.html
{% extends 'events/base.html' %}